repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, pandas-stubs]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests/ -x -q
        language: system
        pass_filenames: false
        always_run: true
